name: Docker Release

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    name: Build and Release Docker Images
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [linux]
        arch: [amd64, arm64]
      fail-fast: false

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: ${{ matrix.os }}/${{ matrix.arch }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ github.sha }}
            ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ matrix.os }}-${{ matrix.arch }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        if: github.ref == 'refs/heads/main'
        with:
          tag_name: release-${{ github.run_number }}
          name: Release ${{ github.run_number }}
          generate_release_notes: true
